project:
  type: website
  output-dir: docs

website:
  title: "IDS 702 - Fall 2025"
  navbar:
    background: "#F16729"
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

