---
title: "Multinomial (Logistic) Regression"
author: "Group member names here (omit absent members)"
output: pdf
editor: visual
---

## Generalized Linear Models

-   Allow us to fit models with different types of outcomes: binary, nominal, ordinal, count

-   Allow us to **perform inference**, i.e., obtain interpretable estimates, quantify uncertainty of those estimates, conduct hypothesis tests

## Multinomial Regression

Define $\pi_j$ as $P(Y=j)$ for a level $j$ of a nominal categorical variable.

The multinomial model is defined as a set of logistic regression models for each probability $\pi_j$ compared to a baseline level:

$$
log(\frac{\pi_{ij}}{\pi_{i1}})=\beta_{0j}+\beta_{1j}x_{i1}+...+\beta_{pj}x_{ip}
$$

What are all of the indices here ( $j$, $p$, and $i$ )?

## Interpretations

Each coefficient estimate has to be interpreted relative to the baseline outcome level

-   If $x_1$ is continuous, $e^{\beta_{1j}}$ is the multiplicative increase/decrease in the **odds** of $Y=j$ vs $Y=1$ (baseline) when increasing $x_1$ by one unit

-   If $x_1$ is categorical, $e^{\beta_{1j}}$ is the odds of $Y=j$ vs $Y=1$ (baseline) for the group with $x_1=1$ compared to the reference group of the covariate

## Exercise

You are an analyst at a large technology company. The company recently introduced a new health insurance provider for its employees. At the beginning of the year, the employees had to choose one of three different health plan products from this provider. You have been asked to determine which factors influenced the choice in product.

The `health_insurance` data set consists of the following fields:

-   `product`: The choice of product of the individual—A, B or C

-   `age`: The age of the individual when they made the choice

-   `gender`: The gender of the individual as stated when they made the choice

-   `household`: The number of people living with the individual in the same household at the time of the choice

-   `position_le